### ISSUE TITLE
todo list

### ISSUE THREAD

**Issue by hai265** [hai265/Group-5-Call-Your-Mother#1]
- [ ]  ContactAdapter to have the calling circle list
- [ ] ContactSettingsActivity so user can edit contact information and save it
- [ ] Save and load the calling circle information so it persists when user closes and opens app
- [x] Notification to notifiy user.
- [ ] click on contact in to do list to open settings or call the contact
